name: slide
description: Slide for Presentation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rinf: ^4.16.3
  protobuf: ^3.1.0
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  flutter_math_fork: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/raytrace.png
    - images/march.png
    - images/torus.png
    - images/marchcode.png